(set-info :status sat)
(set-logic UF)
(declare-sort A) (declare-sort B)
(declare-const x A)
(declare-const y B)
(declare-fun p (A B) Bool)
(assert (p x y))
(assert (forall ((x A) (y B)) true))
(assert (exists ((x A)) true))
(declare-const q Bool)
(assert (or q (not q)))
(assert (and q q))
(assert (not false))
(assert (distinct q false))
(assert (= q q))
(assert (=> false true))

(check-sat)
(exit)
